# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5175923d0db1f86720b82f034571f2268b8a27e9fb363ed99289c5df00dd7f77b1c4753d20dccf349f3826066b93fa09a3c10499e0e93f27cc31bab6e58f553

test:
  secret_key_base: 7f8ea89407445f73dae9df4af3d116992358b4476e84e835877eb3722ee80492951fc31e9733aae84f36558ec9f861fc48a90e740347f0c2c8acde4541ba552c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
